name: ci
# see https://github.com/marketplace/actions/build-and-push-docker-images
on:
  push:
    branches: main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: sitkevij/rust-linux-dev:latest
          # build-args: |
          #   arg1=none
          #   arg2=value2
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
